doc-warnings: true
test-warnings: false
strictness: medium
max-line-length: 80
autodetect: true
python-targets:
  - 3
ignore-paths:
  - docs
  - tests
  - powermate/_version.py
  - powermate/__init__.py
  - versioneer.py
